import { useState, useEffect } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from './useAuth';
import { toast } from '@/hooks/use-toast';

export interface ReconciliationBatch {
  id: string;
  user_id: string;
  batch_id: string;
  source: 'DSP' | 'PRO' | 'YouTube' | 'Other';
  statement_period_start?: string;
  statement_period_end?: string;
  date_received: string;
  total_gross_amount: number;
  statement_file_url?: string;
  status: 'Pending' | 'Imported' | 'Processed';
  notes?: string;
  created_at: string;
  updated_at: string;
}

export function useReconciliationBatches() {
  const [batches, setBatches] = useState<ReconciliationBatch[]>([]);
  const [loading, setLoading] = useState(true);
  const { user } = useAuth();

  const fetchBatches = async () => {
    if (!user) return;
    
    try {
      const { data, error } = await supabase
        .from('reconciliation_batches')
        .select('*')
        .order('created_at', { ascending: false });

      if (error) throw error;
      setBatches(data || []);
    } catch (error: any) {
      console.error('Error fetching batches:', error);
      toast({
        title: "Error",
        description: "Failed to fetch reconciliation batches",
        variant: "destructive",
      });
    } finally {
      setLoading(false);
    }
  };

  const createBatch = async (batchData: Omit<ReconciliationBatch, 'id' | 'user_id' | 'batch_id' | 'created_at' | 'updated_at'>) => {
    if (!user) return null;

    try {
      const { data, error } = await supabase
        .from('reconciliation_batches')
        .insert({
          ...batchData,
          user_id: user.id,
          // batch_id will be auto-generated by trigger
        })
        .select()
        .single();

      if (error) throw error;

      toast({
        title: "Success",
        description: `Reconciliation batch ${data.batch_id} created successfully`,
      });

      await fetchBatches();
      return data;
    } catch (error: any) {
      console.error('Error creating batch:', error);
      toast({
        title: "Error",
        description: "Failed to create reconciliation batch",
        variant: "destructive",
      });
      return null;
    }
  };

  const updateBatch = async (id: string, batchData: Partial<ReconciliationBatch>) => {
    try {
      const { data, error } = await supabase
        .from('reconciliation_batches')
        .update(batchData)
        .eq('id', id)
        .select()
        .single();

      if (error) throw error;

      toast({
        title: "Success",
        description: "Reconciliation batch updated successfully",
      });

      await fetchBatches();
      return data;
    } catch (error: any) {
      console.error('Error updating batch:', error);
      toast({
        title: "Error",
        description: "Failed to update reconciliation batch",
        variant: "destructive",
      });
      return null;
    }
  };

  const deleteBatch = async (id: string) => {
    try {
      const { error } = await supabase
        .from('reconciliation_batches')
        .delete()
        .eq('id', id);

      if (error) throw error;

      toast({
        title: "Success",
        description: "Reconciliation batch deleted successfully",
      });

      await fetchBatches();
    } catch (error: any) {
      console.error('Error deleting batch:', error);
      toast({
        title: "Error",
        description: "Failed to delete reconciliation batch",
        variant: "destructive",
      });
    }
  };

  useEffect(() => {
    fetchBatches();
  }, [user]);

  return {
    batches,
    loading,
    createBatch,
    updateBatch,
    deleteBatch,
    refreshBatches: fetchBatches,
  };
}