import { useState, useEffect } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from './useAuth';
import { toast } from '@/hooks/use-toast';
import { normalizeTerritoryCode } from '@/utils/territoryNormalizer';

export interface RoyaltyAllocation {
  id: string;
  user_id: string;
  royalty_id: string;
  work_id: string;
  batch_id?: string;
  copyright_id?: string;
  song_title: string;
  isrc?: string;
  artist?: string;
  gross_royalty_amount: number;
  controlled_status: 'Controlled' | 'Non-Controlled';
  recoupable_expenses: boolean;
  ownership_splits: any;
  comments?: string;
  // ENCORE Standard Fields
  quarter?: string;
  source?: string;
  revenue_source?: string;
  work_identifier?: string;
  work_writers?: string;
  share?: string;
  media_type?: string;
  media_sub_type?: string;
  country?: string;
  quantity?: string;
  gross_amount?: number;
  net_amount?: number;
  iswc?: string;
  statement_id?: string;
  staging_record_id?: string;
  mapped_data?: any; // Store all original mapped data fields
  created_at: string;
  updated_at: string;
}

// For inserts, royalty_id is auto-generated by database trigger
export type RoyaltyAllocationInsert = Omit<RoyaltyAllocation, 'id' | 'user_id' | 'royalty_id' | 'work_id' | 'created_at' | 'updated_at'> & {
  user_id?: string;
  royalty_id?: string; // Optional for inserts
  work_id?: string; // Optional for inserts
};

export interface RoyaltyWriter {
  id: string;
  royalty_id: string;
  contact_id: string;
  writer_share_percentage: number;
  performance_share: number;
  mechanical_share: number;
  synchronization_share: number;
  created_at: string;
}

export function useRoyaltyAllocations() {
  const [allocations, setAllocations] = useState<RoyaltyAllocation[]>([]);
  const [loading, setLoading] = useState(true);
  const { user } = useAuth();

  const fetchAllocations = async () => {
    if (!user) return;
    
    try {
      const { data, error } = await supabase
        .from('royalty_allocations')
        .select(`
          *,
          reconciliation_batches!royalty_allocations_batch_id_fkey(batch_id, source),
          copyrights(
            work_title,
            work_id,
            copyright_writers(
              writer_name,
              ownership_percentage,
              controlled_status
            )
          )
        `)
        .order('created_at', { ascending: false });

      if (error) throw error;
      setAllocations(data || []);
    } catch (error: any) {
      console.error('Error fetching allocations:', error);
      toast({
        title: "Error",
        description: "Failed to fetch royalties",
        variant: "destructive",
      });
    } finally {
      setLoading(false);
    }
  };

  const createAllocation = async (allocationData: RoyaltyAllocationInsert) => {
    if (!user) return null;

    try {
      console.log('createAllocation called with data:', allocationData);
      
      // Normalize territory before insertion
      const normalizedCountry = allocationData.country 
        ? normalizeTerritoryCode(allocationData.country)
        : undefined;
      
      const insertData = {
        ...allocationData,
        country: normalizedCountry,
        user_id: user.id,
      };
      
      console.log('Final insert data:', insertData);
      
      const { data, error } = await supabase
        .from('royalty_allocations')
        .insert(insertData as any)
        .select()
        .single();

      if (error) throw error;

      toast({
        title: "Success",
        description: `Royalty for "${data.song_title}" created successfully`,
      });

      await fetchAllocations();
      return data;
    } catch (error: any) {
      console.error('Error creating allocation:', error);
      toast({
        title: "Error",
        description: "Failed to create royalty",
        variant: "destructive",
      });
      return null;
    }
  };

  const updateAllocation = async (id: string, allocationData: Partial<RoyaltyAllocation>) => {
    try {
      // Normalize territory if present
      const normalizedData = {
        ...allocationData,
        ...(allocationData.country && {
          country: normalizeTerritoryCode(allocationData.country)
        })
      };
      
      const { data, error } = await supabase
        .from('royalty_allocations')
        .update(normalizedData)
        .eq('id', id)
        .select()
        .single();

      if (error) throw error;

      toast({
        title: "Success",
        description: "Royalty updated successfully",
      });

      await fetchAllocations();
      return data;
    } catch (error: any) {
      console.error('Error updating allocation:', error);
      toast({
        title: "Error",
        description: "Failed to update royalty",
        variant: "destructive",
      });
      return null;
    }
  };

  const deleteAllocation = async (id: string) => {
    try {
      const { error } = await supabase
        .from('royalty_allocations')
        .delete()
        .eq('id', id);

      if (error) throw error;

      toast({
        title: "Success",
        description: "Royalty deleted successfully",
      });

      await fetchAllocations();
    } catch (error: any) {
      console.error('Error deleting allocation:', error);
      toast({
        title: "Error",
        description: "Failed to delete royalty",
        variant: "destructive",
      });
    }
  };

  const addWriterToAllocation = async (royaltyId: string, writerData: Omit<RoyaltyWriter, 'id' | 'royalty_id' | 'created_at'>) => {
    try {
      const { data, error } = await supabase
        .from('royalty_writers')
        .insert({
          ...writerData,
          royalty_id: royaltyId,
        })
        .select()
        .single();

      if (error) throw error;

      toast({
        title: "Success",
        description: "Writer added to royalty",
      });

      return data;
    } catch (error: any) {
      console.error('Error adding writer:', error);
      toast({
        title: "Error",
        description: "Failed to add writer to royalty",
        variant: "destructive",
      });
      return null;
    }
  };

  const removeWriterFromAllocation = async (writerId: string) => {
    try {
      const { error } = await supabase
        .from('royalty_writers')
        .delete()
        .eq('id', writerId);

      if (error) throw error;

      toast({
        title: "Success",
        description: "Writer removed from royalty",
      });
    } catch (error: any) {
      console.error('Error removing writer:', error);
      toast({
        title: "Error",
        description: "Failed to remove writer from royalty",
        variant: "destructive",
      });
    }
  };

  useEffect(() => {
    fetchAllocations();
  }, [user]);

  return {
    allocations,
    loading,
    createAllocation,
    updateAllocation,
    deleteAllocation,
    addWriterToAllocation,
    removeWriterFromAllocation,
    refreshAllocations: fetchAllocations,
  };
}