import { supabase } from '@/integrations/supabase/client';

export interface FixtureResult {
  runId: string;
  contactId: string;
  contractId: string;
  copyrightIds: string[];
  scheduleWorkIds: string[];
  allocationIds: string[];
}

/**
 * Creates deterministic fixtures for the payout reconciliation sanity check.
 *
 * 8 royalty_allocations ($100 gross each) with varying properties:
 * | # | revenue_type | line_type | confidence | rights_basis              | copyright | Bucket       | Reason                      |
 * |---|-------------|-----------|------------|---------------------------|-----------|--------------|------------------------------|
 * | 1 | performance | royalty   | high       | ownership_split_by_right  | CR1       | Allocated    | work splits 70/30            |
 * | 2 | null        | null      | null       | null                      | CR1       | Unpayable    | missing_revenue_type         |
 * | 3 | other       | royalty   | high       | ownership_split_by_right  | CR1       | Needs review | revenue_type_other           |
 * | 4 | performance | royalty   | low        | ownership_split_by_right  | CR1       | Needs review | low_confidence               |
 * | 5 | mechanical  | royalty   | high       | exclude_from_splits       | CR1       | Excluded     | exclude_from_splits          |
 * | 6 | synch       | fee       | high       | ownership_split_by_right  | CR1       | Excluded     | non_royalty_line_type:fee     |
 * | 7 | performance | royalty   | high       | ownership_split_by_right  | CR3       | Allocated    | contract splits 60/40        |
 * | 8 | performance | royalty   | high       | ownership_split_by_right  | CR2       | Unpayable    | invalid_split_totals         |
 *
 * Notes:
 * - royalty_id: auto-generated by set_royalty_id database trigger (BEFORE INSERT).
 *   We provide a placeholder UUID to satisfy the TypeScript Insert type; the trigger overwrites it.
 * - contract_status: defaults to 'draft'. Confirmed: calculatePayoutTotals does NOT filter by status.
 */
export async function createFixtures(runId: string, userId: string): Promise<FixtureResult> {

  // 1. Contact
  const { data: contact, error: contactErr } = await supabase
    .from('contacts')
    .insert({ user_id: userId, name: `Sanity-${runId}`, contact_type: 'writer' })
    .select('id')
    .single();
  if (contactErr || !contact) throw new Error(`Contact insert failed: ${contactErr?.message}`);

  // 2. Contract (status defaults to 'draft' — no status filtering in engine)
  const { data: contract, error: contractErr } = await supabase
    .from('contracts')
    .insert({
      user_id: userId,
      contract_type: 'publishing',
      title: `Sanity-${runId}`,
      counterparty_name: 'Sanity Test',
      notes: runId,
    })
    .select('id')
    .single();
  if (contractErr || !contract) throw new Error(`Contract insert failed: ${contractErr?.message}`);

  // 3. Contract interested parties (contract-level splits: A=60 C, B=40 NC)
  const { error: cipErr } = await supabase
    .from('contract_interested_parties')
    .insert([
      {
        contract_id: contract.id,
        name: `Sanity-${runId}-A`,
        party_type: 'publisher',
        controlled_status: 'C',
        performance_percentage: 60,
        mechanical_percentage: 60,
        synch_percentage: 60,
      },
      {
        contract_id: contract.id,
        name: `Sanity-${runId}-B`,
        party_type: 'writer',
        controlled_status: 'NC',
        performance_percentage: 40,
        mechanical_percentage: 40,
        synch_percentage: 40,
      },
    ]);
  if (cipErr) throw new Error(`Contract parties insert failed: ${cipErr.message}`);

  // 4. Copyrights (3)
  const copyrightInserts = [
    { user_id: userId, work_title: `Sanity-CR1-${runId}`, work_id: `SANITY-${runId}-CR1-${crypto.randomUUID().slice(0, 6)}`, notes: runId },
    { user_id: userId, work_title: `Sanity-CR2-${runId}`, work_id: `SANITY-${runId}-CR2-${crypto.randomUUID().slice(0, 6)}`, notes: runId },
    { user_id: userId, work_title: `Sanity-CR3-${runId}`, work_id: `SANITY-${runId}-CR3-${crypto.randomUUID().slice(0, 6)}`, notes: runId },
  ];
  const { data: copyrights, error: crErr } = await supabase
    .from('copyrights')
    .insert(copyrightInserts)
    .select('id');
  if (crErr || !copyrights || copyrights.length !== 3) {
    throw new Error(`Copyrights insert failed: ${crErr?.message}`);
  }
  const [cr1, cr2, cr3] = copyrights;

  // 5. Schedule works (3)
  const swInserts = [
    { contract_id: contract.id, song_title: `Sanity-SW1-${runId}`, copyright_id: cr1.id, inherits_royalty_splits: false },
    { contract_id: contract.id, song_title: `Sanity-SW2-${runId}`, copyright_id: cr2.id, inherits_royalty_splits: false },
    { contract_id: contract.id, song_title: `Sanity-SW3-${runId}`, copyright_id: cr3.id, inherits_royalty_splits: true },
  ];
  const { data: scheduleWorks, error: swErr } = await supabase
    .from('contract_schedule_works')
    .insert(swInserts)
    .select('id');
  if (swErr || !scheduleWorks || scheduleWorks.length !== 3) {
    throw new Error(`Schedule works insert failed: ${swErr?.message}`);
  }
  const [sw1, sw2] = scheduleWorks;

  // 6. Work parties for SW1: X=70 C, Y=30 NC (valid sum = 100)
  const { error: wp1Err } = await supabase
    .from('contract_work_interested_parties')
    .insert([
      {
        contract_id: contract.id,
        contract_schedule_work_id: sw1.id,
        party_id: crypto.randomUUID(),
        party_name: `Sanity-${runId}-X`,
        party_type: 'writer',
        controlled_status: 'C',
        performance_percentage: 70,
        mechanical_percentage: 70,
        synch_percentage: 70,
      },
      {
        contract_id: contract.id,
        contract_schedule_work_id: sw1.id,
        party_id: crypto.randomUUID(),
        party_name: `Sanity-${runId}-Y`,
        party_type: 'writer',
        controlled_status: 'NC',
        performance_percentage: 30,
        mechanical_percentage: 30,
        synch_percentage: 30,
      },
    ]);
  if (wp1Err) throw new Error(`Work parties SW1 insert failed: ${wp1Err.message}`);

  // 7. Work party for SW2: Z=90 (invalid sum — does not reach 100)
  const { error: wp2Err } = await supabase
    .from('contract_work_interested_parties')
    .insert({
      contract_id: contract.id,
      contract_schedule_work_id: sw2.id,
      party_id: crypto.randomUUID(),
      party_name: `Sanity-${runId}-Z`,
      party_type: 'writer',
      controlled_status: 'C',
      performance_percentage: 90,
      mechanical_percentage: 90,
      synch_percentage: 90,
    });
  if (wp2Err) throw new Error(`Work party SW2 insert failed: ${wp2Err.message}`);

  // 8. Royalty allocations (8 × $100 gross)
  // royalty_id: placeholder UUID — set_royalty_id trigger (BEFORE INSERT) auto-generates it
  const allocations = [
    { revenue_type: 'performance', line_type: 'royalty', revenue_type_confidence: 'high', rights_basis: 'ownership_split_by_right_type', copyright_id: cr1.id },
    { revenue_type: null, line_type: null, revenue_type_confidence: null, rights_basis: null, copyright_id: cr1.id },
    { revenue_type: 'other', line_type: 'royalty', revenue_type_confidence: 'high', rights_basis: 'ownership_split_by_right_type', copyright_id: cr1.id },
    { revenue_type: 'performance', line_type: 'royalty', revenue_type_confidence: 'low', rights_basis: 'ownership_split_by_right_type', copyright_id: cr1.id },
    { revenue_type: 'mechanical', line_type: 'royalty', revenue_type_confidence: 'high', rights_basis: 'exclude_from_splits', copyright_id: cr1.id },
    { revenue_type: 'synch', line_type: 'fee', revenue_type_confidence: 'high', rights_basis: 'ownership_split_by_right_type', copyright_id: cr1.id },
    { revenue_type: 'performance', line_type: 'royalty', revenue_type_confidence: 'high', rights_basis: 'ownership_split_by_right_type', copyright_id: cr3.id },
    { revenue_type: 'performance', line_type: 'royalty', revenue_type_confidence: 'high', rights_basis: 'ownership_split_by_right_type', copyright_id: cr2.id },
  ].map((alloc) => ({
    user_id: userId,
    song_title: `Sanity-${runId}`,
    gross_royalty_amount: 100,
    country: 'US',
    comments: runId,
    royalty_id: crypto.randomUUID(), // placeholder — overwritten by set_royalty_id trigger
    ...alloc,
  }));

  const { data: allocData, error: allocErr } = await supabase
    .from('royalty_allocations')
    .insert(allocations)
    .select('id');
  if (allocErr || !allocData) throw new Error(`Allocations insert failed: ${allocErr?.message}`);

  return {
    runId,
    contactId: contact.id,
    contractId: contract.id,
    copyrightIds: copyrights.map((c) => c.id),
    scheduleWorkIds: scheduleWorks.map((s) => s.id),
    allocationIds: allocData.map((a) => a.id),
  };
}

/**
 * Cleanup all fixtures created by a specific run.
 * Deletes in reverse dependency order. Each step wrapped in try/catch
 * so partial cleanup still proceeds.
 */
export async function cleanupFixtures(runId: string, userId: string): Promise<string[]> {
  const errors: string[] = [];

  const tryDelete = async (label: string, fn: () => Promise<void>) => {
    try {
      await fn();
    } catch (e: any) {
      errors.push(`${label}: ${e.message}`);
    }
  };

  // Get contract id for cascading deletes
  const { data: contracts } = await supabase
    .from('contracts')
    .select('id')
    .eq('notes', runId)
    .eq('user_id', userId);
  const contractIds = (contracts || []).map((c) => c.id);

  // Royalty allocations (by comments tag)
  await tryDelete('royalty_allocations', async () => {
    await supabase.from('royalty_allocations').delete().eq('comments', runId).eq('user_id', userId);
  });

  // Work interested parties (by party_name pattern)
  await tryDelete('contract_work_interested_parties', async () => {
    if (contractIds.length > 0) {
      await supabase
        .from('contract_work_interested_parties')
        .delete()
        .in('contract_id', contractIds);
    }
  });

  // Schedule works
  await tryDelete('contract_schedule_works', async () => {
    if (contractIds.length > 0) {
      await supabase
        .from('contract_schedule_works')
        .delete()
        .in('contract_id', contractIds);
    }
  });

  // Contract interested parties
  await tryDelete('contract_interested_parties', async () => {
    if (contractIds.length > 0) {
      await supabase
        .from('contract_interested_parties')
        .delete()
        .in('contract_id', contractIds);
    }
  });

  // Contracts
  await tryDelete('contracts', async () => {
    await supabase.from('contracts').delete().eq('notes', runId).eq('user_id', userId);
  });

  // Copyrights
  await tryDelete('copyrights', async () => {
    await supabase.from('copyrights').delete().eq('notes', runId).eq('user_id', userId);
  });

  // Contacts
  await tryDelete('contacts', async () => {
    await supabase.from('contacts').delete().eq('name', `Sanity-${runId}`).eq('user_id', userId);
  });

  return errors;
}
