import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { useToast } from "@/hooks/use-toast";
import { supabase } from "@/integrations/supabase/client";
import { TestTube, Copy } from "lucide-react";

export function ClientPortalTestHelper() {
  const { toast } = useToast();
  const [testEmail, setTestEmail] = useState("test@example.com");
  const [invitationToken, setInvitationToken] = useState("");

  const createTestInvitation = async () => {
    try {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) {
        toast({
          title: "Error",
          description: "You must be logged in to create test invitations",
          variant: "destructive"
        });
        return;
      }

      // Create test invitation - the invitation_token will be auto-generated by the trigger
      const { data, error } = await supabase
        .from('client_invitations')
        .insert({
          email: testEmail,
          permissions: {
            contracts: { enabled: true },
            copyright: { enabled: true },
            royalties: { enabled: true },
            'sync-licensing': { enabled: true }
          },
          subscriber_user_id: user.id,
          expires_at: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(), // 7 days
          invitation_token: '' // Will be auto-generated by trigger
        })
        .select()
        .single();

      if (error) {
        toast({
          title: "Error",
          description: error.message,
          variant: "destructive"
        });
        return;
      }

      setInvitationToken(data.invitation_token);
      toast({
        title: "Success",
        description: "Test invitation created! Use the token below to test.",
      });
    } catch (error) {
      console.error('Error creating test invitation:', error);
      toast({
        title: "Error",
        description: "Failed to create test invitation",
        variant: "destructive"
      });
    }
  };

  const copyInvitationUrl = () => {
    if (!invitationToken) return;
    const url = `${window.location.origin}/client-portal?token=${invitationToken}`;
    navigator.clipboard.writeText(url);
    toast({
      title: "Copied",
      description: "Invitation URL copied to clipboard",
    });
  };

  const acceptInvitation = async () => {
    if (!invitationToken) return;
    
    try {
      const response = await fetch(`/api/accept-invitation`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ token: invitationToken })
      });

      if (response.ok) {
        toast({
          title: "Success",
          description: "Invitation accepted! You now have client portal access.",
        });
      } else {
        toast({
          title: "Error",
          description: "Failed to accept invitation",
          variant: "destructive"
        });
      }
    } catch (error) {
      console.error('Error accepting invitation:', error);
      toast({
        title: "Error",
        description: "Failed to accept invitation",
        variant: "destructive"
      });
    }
  };

  return (
    <Card>
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <TestTube className="h-5 w-5" />
          Client Portal Test Helper
        </CardTitle>
        <CardDescription>
          Quick tools to test the client portal functionality
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        <div>
          <Label htmlFor="testEmail">Test Email</Label>
          <Input
            id="testEmail"
            value={testEmail}
            onChange={(e) => setTestEmail(e.target.value)}
            placeholder="test@example.com"
          />
        </div>

        <Button onClick={createTestInvitation} className="w-full">
          Create Test Invitation
        </Button>

        {invitationToken && (
          <div className="space-y-2">
            <Label>Invitation Token</Label>
            <div className="flex gap-2">
              <Input value={invitationToken} readOnly />
              <Button size="icon" variant="outline" onClick={copyInvitationUrl}>
                <Copy className="h-4 w-4" />
              </Button>
            </div>
            <p className="text-sm text-muted-foreground">
              Use this token to test the client portal access
            </p>
          </div>
        )}

        <div className="border-t pt-4">
          <h4 className="font-medium mb-2">Test Instructions:</h4>
          <ol className="text-sm text-muted-foreground space-y-1">
            <li>1. Create a test invitation above</li>
            <li>2. Copy the invitation URL</li>
            <li>3. Open in new tab or send to test user</li>
            <li>4. Visit /client-portal to see the portal</li>
          </ol>
        </div>
      </CardContent>
    </Card>
  );
}