-- Remove quarterly balance reports that were auto-generated by the old logic
-- These are reports with all zero values that were created automatically when payees were added
-- rather than being created when actual payouts were marked as paid

DELETE FROM quarterly_balance_reports 
WHERE 
  -- Reports with all zero financial values (indicating auto-generated placeholders)
  royalties_amount = 0 
  AND expenses_amount = 0 
  AND payments_amount = 0 
  AND opening_balance = 0 
  AND closing_balance = 0
  -- Only delete reports that were marked as calculated but have no actual data
  AND is_calculated = true
  -- Additional safety: only delete recent reports from the auto-initialization period
  AND created_at >= '2025-09-21'::date;